blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: https://github.com/supershadoe/delta/discussions
    about: Ask questions about the app in general or any other help related to the app.
