name: Linting/Formatting
description: Runs lint and format checks
inputs:
  cache-encryption-key:
    description: 'Encryption key for the configuration cache'
    required: false
  read-only-cache:
    description: 'Whether to use a read-only cache for this step'
    required: false
    default: 'false'
runs:
  using: composite
  steps:
    - name: Custom gradle setup
      uses: ./.github/actions/gradle-setup
      with:
        cache-encryption-key: ${{ inputs.cache-encryption-key || '' }}
    - name: Check for formatting issues
      shell: bash
      run: ./gradlew spotlessCheck
