name: delta-ci
on:
  push:
    branches:
      - main
    tags:
      - v*
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: write
jobs:
  build-apk:
    name: Build app
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Configure signing key
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          SIGN_BASE64: ${{ secrets.SIGN_BASE64 }}
        run: |
          echo $KEYSTORE_BASE64 | base64 -d > app/sign.keystore
          echo $SIGN_BASE64 | base64 -d > app/sign.json
      - name: Lint check
        run: ./gradlew spotlessCheck
      - name: Build app
        run: ./gradlew assembleDefaultKeySignedRelease
      - name: Delete APK before uploading new APK
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.actions.deleteArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              artifact_id: ${{ steps.upload-apk.outputs.artifact-id }},
            });
      - name: Upload APK
        id: upload-apk
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: app/build/outputs/apk/defaultKeySigned/release/app-defaultKeySigned-release.apk
  dep-subm:
    name: Dependency submission
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4
