name: delta-ci
on:
  workflow_call:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - '*.txt'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/gradle-setup
      - name: Run unit tests
        run: ./gradlew testReleaseUnitTest
  dependency-graph-submission:
    name: Dependency graph submission
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/gradle-setup
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4
  lint-format:
    name: 'Linting/Formatting'
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/gradle-setup
      - name: Check for formatting issues
        run: ./gradlew spotlessCheck
  build-apk:
    name: Build app
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/gradle-setup
      - name: Decode signing keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: echo $KEYSTORE_BASE64 | base64 -d > app/sign.keystore
      - name: Configure signing key
        env:
          SIGN_BASE64: ${{ secrets.SIGN_BASE64 }}
        run: echo $SIGN_BASE64 | base64 -d > app/sign.json
      - name: Build app
        run: ./gradlew assembleDefaultKeySignedRelease
      - name: Move apk to root
        run: |
          mv app/build/outputs/apk/defaultKeySigned/release/app-defaultKeySigned-release.apk \
            app-release.apk
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: app-release.apk
          retention-days: 7
          if-no-files-found: error
