name: delta-ci
on:
  push:
    branches:
      - main
    tags:
      - v*
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-apk:
    name: Build app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Configure signing key
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          SIGN_BASE64: ${{ secrets.SIGN_BASE64 }}
        run: |
          echo $KEYSTORE_BASE64 | base64 -d > app/sign.keystore
          echo $SIGN_BASE64 | base64 -d > app/sign.json
      - name: Lint check
        run: ./gradlew spotlessCheck
      - name: Build app
        run: ./gradlew assembleDefaultKeySignedRelease
      - name: Upload APK
        id: upload-apk
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: app/build/outputs/apk/defaultKeySigned/release/app-defaultKeySigned-release.apk
          retention-days: 7
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    needs: [build-apk]
    if: startsWith(github.ref, 'refs/tags/') && github.repository == 'supershadoe/delta'
    steps:
      - name: Download APK
        uses: actions/download-artifact@v4
        with:
          name: app
      - name: Calculate checksum
        run: |
          sha256sum app-defaultKeySigned-release.apk |\
            xargs -I "{}" echo "SHA_OUT='{}'" |\
            tee $GITHUB_ENV
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          draft: true
          prerelease: false
          files: |
            app-defaultKeySigned-release.apk
          discussion_category_name: Announcements
          body: |
            ### Message
            To be filled.

            ### Checksum
            ```sh
            ${{ env.SHA_OUT }}
            ```
            Check the checksum after downloading the APK using `sha256sum` to
            ensure integrity of the file.
