name: delta-ci
on:
  push:
    branches:
      - main
    tags:
      - v*
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  pre-build-job:
    name: Pre-build job
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      - name: Setup git
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email \
            "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Run spotless (auto-formatter)
        run: ./gradlew spotlessApply
      - name: Run unit tests
        run: ./gradlew testReleaseUnitTest
      - name: Generate diff and push to main
        uses: |
          if ! git diff --exit-code; then
            git commit -am "Auto-formatted changes"
            git push
          fi
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4
  build-apk:
    name: Build app
    runs-on: ubuntu-latest
    needs: [pre-build-job]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      - name: Decode signing keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: echo $KEYSTORE_BASE64 | base64 -d > app/sign.keystore
      - name: Configure signing key
        env:
          SIGN_BASE64: ${{ secrets.SIGN_BASE64 }}
        run: echo $SIGN_BASE64 | base64 -d > app/sign.json
      - name: Build app
        run: ./gradlew assembleDefaultKeySignedRelease
      - name: Move apk to root
        run: |
          mv app/build/outputs/apk/defaultKeySigned/release/app-defaultKeySigned-release.apk \
            app-release.apk
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: app-release.apk
          retention-days: 7
          if-no-files-found: error
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    needs: [build-apk]
    permissions:
      contents: write
      discussions: write
    if: startsWith(github.ref, 'refs/tags/') && github.repository == 'supershadoe/delta'
    steps:
      - name: Download APK
        uses: actions/download-artifact@v4
        with:
          name: app
      - name: Calculate checksum
        run: |
          sha256sum app-release.apk | xargs -I "{}" echo "SHA_OUT='{}'" |\
            tee $GITHUB_ENV
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          draft: true
          prerelease: false
          files: |
            app-release.apk
          discussion_category_name: Announcements
          body: |
            ### Message
            To be filled.

            ### Checksum
            ```sh
            ${{ env.SHA_OUT }}
            ```
            Check the checksum after downloading the APK using `sha256sum` to
            ensure integrity of the file.
